"""
Генератор синтетических выходных данных FreeSurfer.
Создаёт папку test_data/subject_001/ с файлами:
  - aseg.stats    (формат как в stats/aseg.stats)
  - aparc.stats   (формат как в stats/?h.aparc.stats)
  - brain.mgz     (минимальный NIfTI 10x10x10)
"""

import os
import random
from pathlib import Path

import numpy as np
import nibabel as nib


# === Конфигурация синтетических данных ===

OUTPUT_DIR = Path("test_data/subject_001")

# Подкорковые структуры (для aseg.stats) — реальные имена FreeSurfer
ASEG_STRUCTURES = [
    ("Left-Hippocampus",      4200, 500),
    ("Right-Hippocampus",     4300, 500),
    ("Left-Thalamus-Proper",  7800, 700),
    ("Right-Thalamus-Proper", 7900, 700),
    ("Left-Putamen",          5800, 600),
    ("Right-Putamen",         5900, 600),
]

# Кортикальные структуры (для aparc.stats) — реальные имена из Desikan-Killiany
APARC_STRUCTURES = [
    ("lh-bankssts",                   2.5, 0.2),
    ("lh-caudalanteriorcingulate",    2.7, 0.2),
    ("lh-cuneus",                     2.3, 0.2),
    ("rh-bankssts",                   2.5, 0.2),
    ("rh-caudalanteriorcingulate",    2.7, 0.2),
    ("rh-cuneus",                     2.3, 0.2),
]


def generate_aseg_stats(output_path: Path, seed: int = 42):
    """
    Генерирует aseg.stats в формате, приближенном к реальному FreeSurfer.
    Колонки: Index, SegId, NVoxels, Volume_mm3, StructName,
             normMean, normStdDev, normMin, normMax, normRange
    """
    rng = random.Random(seed)

    lines = []
    lines.append("# ASEG statistics (synthetic data for QC prototype)")
    lines.append("# Generated by generate_fake_data.py")
    lines.append("#")
    lines.append("# ColHeaders: Index SegId NVoxels Volume_mm3 StructName "
                  "normMean normStdDev normMin normMax normRange")
    lines.append("#")

    for idx, (name, mean, std) in enumerate(ASEG_STRUCTURES, start=1):
        seg_id = idx * 10 + rng.randint(1, 9)
        nvoxels = rng.randint(3000, 12000)
        volume = int(rng.gauss(mean, std * 0.3))  # случайное отклонение от нормы
        volume = max(100, volume)
        norm_min = mean - 3 * std
        norm_max = mean + 3 * std
        norm_range = norm_max - norm_min
        lines.append(
            f"  {idx}  {seg_id}  {nvoxels}  {volume:.1f}  {name}  "
            f"{mean:.1f}  {std:.1f}  {norm_min:.1f}  {norm_max:.1f}  {norm_range:.1f}"
        )

    output_path.write_text("\n".join(lines), encoding="utf-8")


def generate_aparc_stats(output_path: Path, seed: int = 42):
    """
    Генерирует aparc.stats в формате, приближенном к реальному ?h.aparc.stats.
    Колонки: StructName, NumVert, SurfArea, GrayVol, ThickAvg, ThickStd,
             MeanCurv, GausCurv, FoldInd, CurvInd
    """
    rng = random.Random(seed + 1)

    lines = []
    lines.append("# APARC statistics (synthetic data for QC prototype)")
    lines.append("# Generated by generate_fake_data.py")
    lines.append("#")
    lines.append("# ColHeaders: StructName NumVert SurfArea GrayVol ThickAvg "
                  "ThickStd MeanCurv GausCurv FoldInd CurvInd")
    lines.append("#")

    for idx, (name, mean, std) in enumerate(APARC_STRUCTURES, start=1):
        num_vert = rng.randint(800, 3000)
        surf_area = round(rng.uniform(800, 3500), 1)
        gray_vol = round(rng.uniform(2000, 6000), 1)
        thickness = round(rng.gauss(mean, std * 0.3), 2)
        thickness = max(1.0, min(4.0, thickness))
        thick_std = round(rng.uniform(0.1, 0.4), 2)
        mean_curv = round(rng.uniform(0.1, 0.3), 4)
        gaus_curv = round(rng.uniform(0.01, 0.05), 4)
        fold_ind = round(rng.uniform(10, 40), 1)
        curv_ind = round(rng.uniform(2.0, 3.5), 1)

        lines.append(
            f"  {name}  {num_vert}  {surf_area}  {gray_vol}  {thickness}  "
            f"{thick_std}  {mean_curv}  {gaus_curv}  {fold_ind}  {curv_ind}"
        )

    output_path.write_text("\n".join(lines), encoding="utf-8")


def generate_brain_mgz(output_path: Path):
    """Создаёт минимальный NIfTI-файл 10x10x10, заполненный нулями."""
    data = np.zeros((10, 10, 10), dtype=np.int16)
    # Добавляем небольшой градиент, чтобы срез не был абсолютно пустым
    for z in range(10):
        data[:, :, z] = z * 10
    affine = np.eye(4)
    img = nib.Nifti1Image(data, affine)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    nib.save(img, str(output_path))


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"[1/3] Generating aseg.stats -> {OUTPUT_DIR / 'aseg.stats'}")
    generate_aseg_stats(OUTPUT_DIR / "aseg.stats")
    print(f"[2/3] Generating aparc.stats -> {OUTPUT_DIR / 'aparc.stats'}")
    generate_aparc_stats(OUTPUT_DIR / "aparc.stats")
    print(f"[3/3] Generating brain.mgz -> {OUTPUT_DIR / 'brain.mgz'}")
    generate_brain_mgz(OUTPUT_DIR / "brain.mgz")
    print("Done. Synthetic data created in:", OUTPUT_DIR.resolve())


if __name__ == "__main__":
    main()
